import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  facets: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    alignSelf: 'stretch',
    borderRadius: 2,
    marginBottom: 12,
    shadowColor: 'rgb(25,25,25)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    paddingBottom: 8,
    borderColor: 'rgb(200,200,200)',
    borderWidth: StyleSheet.hairlineWidth,
  },
  facetsDimension: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    alignSelf: 'stretch',
    borderRadius: 2,
    marginBottom: 12,
    shadowColor: 'rgb(25,25,25)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    paddingBottom: 8,
    borderColor: 'rgb(200,200,200)',
    borderWidth: StyleSheet.hairlineWidth,
  },
  facetHeader: {
    display: 'flex',
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingLeft:10,
    paddingTop:5,
    paddingBottom:5,
    shadowColor: 'rgb(25,25,25)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    borderBottomColor: 'rgb(200,200,200)',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  name: {
    color: 'rgb(75, 75, 75)',
    marginLeft: 5,
    fontSize: 13,
  },
  icon: {
    width:12,
    height:12,
  },
  categoryLabel: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    borderWidth: 0,
    height:20,
    paddingLeft: 8,
    backgroundColor: 'white',
  },
  dimensionLabel: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignSelf: 'stretch',
    alignItems: 'center',
    flexDirection: 'row',
    paddingLeft: 0,
    marginBottom:0,
    borderWidth: 0,
    height:8,
    backgroundColor: 'transparent',
  },
  labelText:
  {
    color: 'rgb(75, 75, 75)',
    fontSize: 10,
    fontWeight: 'normal',
  },
  labelIconContainer: {
    display: 'flex',
    width:30,
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
  },
  emptyIconContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  listItem: {
    display: 'flex',
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'flex-start',
    height:30,
    padding:0,
  }
});